services:
  - type: web
    name: girlsnav-webapp
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        python3-dev \
        libsm6 \
        libxext6 \
        libxrender-dev \
        libglib2.0-0
      pip install numpy==1.24.3
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0